version: '3.8'

services:

  flask:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.flask
    ports:
      - "5000:5000"
    volumes:
      - ./ml-server:/app


  nextjs:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./iwdb-frontend:/app
